apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: samplewebapp
  namespace: default
  labels:
    app: samplewebapp
spec:
  replicas: 1
  selector:
    matchLabels:
        app: samplewebapp
  template:
    metadata:
      name: samplewebapp
      labels:
        app: samplewebapp
    spec:
      containers:
      - name: samplewebapp
        image: YOUR_DOCKER_IMAGE
        env:
        - name: DatabaseConnectionStringFromKubernetesEnvVariable
          valueFrom:
            configMapKeyRef:
              name: samplewebapp-configmap-1
              key: DatabaseConnectionStringFromKubernetesEnvVariable
        volumeMounts:
        - name: samplewebapp-configmap-2
          mountPath: /app/AppConfig.json
          subPath: AppConfig.json
        resources: {}
        terminationMessagePath: "/dev/termination-log"
        terminationMessagePolicy: File
        imagePullPolicy: Always
        securityContext:
          privileged: false
      volumes:
      - name: samplewebapp-configmap-2
        configMap:
            name: samplewebapp-configmap-2
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler